import { Jersey_10 , Geist_Mono} from "next/font/google";
import { Particles } from "@/components/magicui/particles";
import "./globals.css";

const geistSans = Jersey_10({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: '400',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geistSans.className}>
        {/* Background Particles */}
        <div className="fixed inset-0 -z-10 h-screen w-screen bg-black">
          <Particles size={3} quantity={100} color={["#ffffff","#dd3333"]} className="h-full w-full" />
        </div>
        {/* Main Content */}
        {children}
      </body>
    </html>
  );
}
