import { Jersey_10, Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import { Particles } from "@/components/magicui/particles";
import "./globals.css";
import { AnimatedGridPattern } from "@/components/magicui/animated-grid-pattern";

const geistSans = Jersey_10({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: '400',
});

const geistMono = Geist({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="fixed inset-0 -z-10 h-screen w-screen bg-white">
          {/* <Particles size={3} quantity={100} color={["#555555","#dd0000"]} className="h-full w-full" /> */}
          <AnimatedGridPattern
            numSquares={30}
            maxOpacity={0.3}
            duration={1}
            repeatDelay={0.5}
            className={cn(
              // "[mask-image:radial-gradient(90vh_circle_at_center,white,transparent)]",
              "inset-x-0 inset-y-[-30%] h-[200%] skew-y-5",
            )}
          />
        </div>
        {children}
      </body>
    </html>
  );
}
